/*
 * This file is generated by jOOQ.
 */
package com.example.reactive.demo.domain.db.tables.records;


import com.example.reactive.demo.domain.db.tables.TestEntity;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestEntityRecord extends UpdatableRecordImpl<TestEntityRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.test_entity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test_entity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.test_entity.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test_entity.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.test_entity.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.test_entity.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TestEntity.TEST_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return TestEntity.TEST_ENTITY.KEY;
    }

    @Override
    public Field<String> field3() {
        return TestEntity.TEST_ENTITY.VALUE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public TestEntityRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TestEntityRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public TestEntityRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public TestEntityRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestEntityRecord
     */
    public TestEntityRecord() {
        super(TestEntity.TEST_ENTITY);
    }

    /**
     * Create a detached, initialised TestEntityRecord
     */
    public TestEntityRecord(Long id, String key, String value) {
        super(TestEntity.TEST_ENTITY);

        setId(id);
        setKey(key);
        setValue(value);
    }
}
