/*
 * This file is generated by jOOQ.
 */
package com.example.reactive.demo.domain.db;


import com.example.reactive.demo.domain.db.tables.FlywaySchemaHistory;
import com.example.reactive.demo.domain.db.tables.TestEntity;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX__TEST_ENTITY__NAME = Internal.createIndex(DSL.name("idx__test_entity__name"), TestEntity.TEST_ENTITY, new OrderField[] { TestEntity.TEST_ENTITY.KEY }, false);
}
