/*
 * This file is generated by jOOQ.
 */
package com.example.reactive.demo.domain.db;


import com.example.reactive.demo.domain.db.tables.FlywaySchemaHistory;
import com.example.reactive.demo.domain.db.tables.Person;
import com.example.reactive.demo.domain.db.tables.TestEntity;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>public.test_entity</code>.
     */
    public static final TestEntity TEST_ENTITY = TestEntity.TEST_ENTITY;
}
