/*
 * This file is generated by jOOQ.
 */
package com.example.reactive.demo.domain.db.tables;


import com.example.reactive.demo.domain.db.Indexes;
import com.example.reactive.demo.domain.db.Keys;
import com.example.reactive.demo.domain.db.Public;
import com.example.reactive.demo.domain.db.tables.records.TestEntityRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestEntity extends TableImpl<TestEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_entity</code>
     */
    public static final TestEntity TEST_ENTITY = new TestEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestEntityRecord> getRecordType() {
        return TestEntityRecord.class;
    }

    /**
     * The column <code>public.test_entity.id</code>.
     */
    public final TableField<TestEntityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.test_entity.key</code>.
     */
    public final TableField<TestEntityRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.test_entity.value</code>.
     */
    public final TableField<TestEntityRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(2048), this, "");

    private TestEntity(Name alias, Table<TestEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private TestEntity(Name alias, Table<TestEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.test_entity</code> table reference
     */
    public TestEntity(String alias) {
        this(DSL.name(alias), TEST_ENTITY);
    }

    /**
     * Create an aliased <code>public.test_entity</code> table reference
     */
    public TestEntity(Name alias) {
        this(alias, TEST_ENTITY);
    }

    /**
     * Create a <code>public.test_entity</code> table reference
     */
    public TestEntity() {
        this(DSL.name("test_entity"), null);
    }

    public <O extends Record> TestEntity(Table<O> child, ForeignKey<O, TestEntityRecord> key) {
        super(child, key, TEST_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX__TEST_ENTITY__NAME);
    }

    @Override
    public Identity<TestEntityRecord, Long> getIdentity() {
        return (Identity<TestEntityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TestEntityRecord> getPrimaryKey() {
        return Keys.TEST_ENTITY_PKEY;
    }

    @Override
    public TestEntity as(String alias) {
        return new TestEntity(DSL.name(alias), this);
    }

    @Override
    public TestEntity as(Name alias) {
        return new TestEntity(alias, this);
    }

    @Override
    public TestEntity as(Table<?> alias) {
        return new TestEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(String name) {
        return new TestEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(Name name) {
        return new TestEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestEntity rename(Table<?> name) {
        return new TestEntity(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
